version: '3.8'

services:
  # Redis - The High-Speed Leaderboard Engine
  redis:
    image: redis:alpine
    container_name: leaderboard-redis
    ports:
      - "6379:6379"
    restart: always

  # MongoDB - The Permanent History Store
  mongodb:
    image: mongo:latest
    container_name: leaderboard-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: leaderboard_db
    restart: always
  
  app:
    build: .
    container_name: leaderboard-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/leaderboard_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your_secret
      ADMIN_PASSW: admin123
      ADMIN_EMAIL: admin@admin.com
    depends_on:
      - mongodb
      - redis
    restart: always

  

volumes:
  mongo-data: